name:                ch-otp
version:             0.1.0.0
github:              "githubuser/ch-otp"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/ch-otp#readme>

dependencies:
- base >= 4.7 && < 5
- distributed-process >=0.5.0 && <0.8
- distributed-process-simplelocalnet >=0.2.4 && <0.3
- network-transport >=0.5 && <0.6
- network-transport-tcp >=0.4 && <0.7
- binary

library:
  source-dirs: src

executables:
  ch-otp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch-otp

tests:
  ch-otp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ch-otp
